import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { library, type IconName } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowDown,
  faArrowTrendUp,
  faArrowUp,
  faBagShopping,
  faBuildingColumns,
  faCalendar,
  faCalendarDays,
  faCar,
  faChartLine,
  faChartPie,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCirclePlus,
  faCoins,
  faCreditCard,
  faEarthAsia,
  faEllipsis,
  faFileInvoiceDollar,
  faFilm,
  faGasPump,
  faGear,
  faGift,
  faGraduationCap,
  faHeartPulse,
  faHome,
  faMoneyBillWave,
  faPalette,
  faPencil,
  faPlane,
  faPlus,
  faRotateLeft,
  faSpa,
  faTag,
  faUtensils,
  faWallet,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faArrowDown,
  faArrowTrendUp,
  faArrowUp,
  faBagShopping,
  faBuildingColumns,
  faCalendar,
  faCalendarDays,
  faCar,
  faChartLine,
  faChartPie,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCirclePlus,
  faCoins,
  faCreditCard,
  faEarthAsia,
  faEllipsis,
  faFileInvoiceDollar,
  faFilm,
  faGasPump,
  faGear,
  faGift,
  faGraduationCap,
  faHeartPulse,
  faHome,
  faMoneyBillWave,
  faPalette,
  faPencil,
  faPlane,
  faPlus,
  faRotateLeft,
  faSpa,
  faTag,
  faUtensils,
  faWallet,
  faXmark,
)

export function Icon({ name, className }: { name: string; className?: string }) {
  return <FontAwesomeIcon icon={['fas', name.replace('fa-', '') as IconName]} className={className} />
}
